[package]
name = "iterating_over_collections"
version = "0.1.0"
edition = "2021"
default-run = "iterating_over_collections"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
