[package]
name = "function_pointers"
version = "0.1.0"
edition = "2021"
default-run = "function_pointers"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
