[package]
name = "message_passing_between_threads"
version = "0.1.0"
edition = "2021"
default-run = "message_passing_between_threads"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
