[package]
name = "iterator_pattern"
version = "0.1.0"
edition = "2021"
default-run = "iterator_pattern"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
